CREATE DATABASE IF NOT EXISTS SecurityDemoDb;
USE SecurityDemoDb;

-- 1. Bảng VaiTro (Roles)
CREATE TABLE IF NOT EXISTS VaiTro (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    TenVaiTro VARCHAR(50) NOT NULL UNIQUE,
    MoTa VARCHAR(255) NULL
);

-- 2. Bảng TaiKhoan (Accounts)
CREATE TABLE IF NOT EXISTS TaiKhoan (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    TenDangNhap VARCHAR(50) NOT NULL UNIQUE,
    MatKhauHash VARCHAR(255) NOT NULL,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 3. Bảng NguoiDung (Users details)
CREATE TABLE IF NOT EXISTS NguoiDung (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    HoTen VARCHAR(100) NOT NULL,
    Tuoi INT NULL,
    QueQuan VARCHAR(150) NULL,
    NoiSinh VARCHAR(150) NULL,
    TaiKhoanId INT NOT NULL,
    VaiTroId INT NULL,
    FOREIGN KEY (TaiKhoanId) REFERENCES TaiKhoan(Id) ON DELETE CASCADE,
    FOREIGN KEY (VaiTroId) REFERENCES VaiTro(Id) ON DELETE SET NULL
);
